name: 'Verify and Release Beta'

on:
  push:
    branches:
      - next

jobs:
  verify:
    uses: trendyol/baklava/.github/workflows/verify.yml@next
    secrets: inherit
  release:
    uses: trendyol/baklava/.github/workflows/release.yml@next
    needs: verify
  chromatic:
    uses: trendyol/baklava/.github/workflows/publish-chromatic.yml@next
    needs: verify
